### ISSUE TITLE
Block texts to be moved in twill

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#199]
We need to make the following text blocks editable from Twill: 

https://impreunapentrusanatate.ro/ro/request-services
- description under the title. 
- info text. 

https://impreunapentrusanatate.ro/ro/get-involved 
- description text

https://impreunapentrusanatate.ro/ro/clinics?
- big description 
- subtitle  (Clinici) 
- subtitle description 

Remove fields from language files. 

TODO after deploy for Marius: 
- update texts in twill, with values from language files.

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
@andreipetcu I have deployed the texts above, but there is one more I missed. It was the same with the one in clinics list, but I think it should be different now, so we need a new entry in twill. 
Is this text in clinic details page:
https://impreunapentrusanatate.ro/ro/clinics/spitalul-universitar-vall-dhebron-barcelona

> Fie că ai fost diagnosticat cu cancer sau cu o altă boală gravă, aici poți consulta lista serviciilor medicale din țară și din străinătate, pentru a găsi informații despre aproximativ 400 de clinici și spitale din 21 de țări, de pe 3 continente. Vei avea, într-un singur loc, detalii legate de patologii tratate, medici și specialiști, date de contact, dar și informații despre transport sau cazare, totul pentru ca tu să afli răspunsul la întrebările tale și șansa de a beneficia de cel mai bun tratament! acest formular.

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
Deployed on live. Looks good.
