### ISSUE TITLE
Setup sentry

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#201]
We have the project created in sentry.io. 
Attached are the instructions to configure it for laravel project. 

We want to be able to catch errors and have details to investigate. 

[Configure Laravel - impreunapentrusanatate - Sentry.pdf](https://github.com/code4romania/AcCES/files/5689186/Configure.Laravel.-.eduacces.-.Sentry.pdf)

I have added `SENTRY_LARAVEL_DSN` secret in github

**Comment by andreipetcu** [comment]
Done on development branch. Make sure to setup the project in sentry as well.

**Comment by mariusghitoiu** [comment]
Deployed on live.
