### ISSUE TITLE
New email field for clinics

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#207]
We want to add a new email field for clinics. This is like a general email ex: office@.

This should be in admin on add/edit clinic under **Număr de telefon:** in clinic details section.

On view in admin and in frontend should be in section "Detalii despre clinica" / "Detalii clinica" under **Phone**.

Make sure we apply correct validation rules. 

This should be optional.

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
Deployed in production.
