### ISSUE TITLE
Phone number add/edit issues

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#208]
- [x] In "Adauga Clinica" form in admin when we select country prefix to contact person phone and press save we get attached error. 

![1](https://user-images.githubusercontent.com/147089/105150427-6c9f1700-5b0d-11eb-92c9-e8271175c9ee.jpg)

- [x] If the country prefix is contained in the phone number on edit it these characters are removed from phone number. See attached video

https://user-images.githubusercontent.com/147089/105150600-a3752d00-5b0d-11eb-8437-25e15a7ec941.mov

- [x] Remove asterix on non mandatory fields from clinic form on **Contact person details**

**Comment by andreipetcu** [comment]
Done on development branch.

**Comment by mariusghitoiu** [comment]
Looks good. Deployed in production.
