### ISSUE TITLE
Handle slug differently for clinics with the same name

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#209]
If we add multiple clinics with the same name we want to add an autoincrement at the end and allow them to have the same name:
Ex: 
We want to have this clinic  https://impreunapentrusanatate.ro/ro/clinics/spitalul-university-college multiple times, so https://impreunapentrusanatate.ro/ro/clinics/spitalul-university-college-transplant-adulti would become https://impreunapentrusanatate.ro/ro/clinics/spitalul-university-college-1 and so on. 

The name will be identical.

**Comment by andreipetcu** [comment]
Done on development branch.

**Comment by mariusghitoiu** [comment]
Looks good. Deployed in production.
