### ISSUE TITLE
Improvements on Clinic details page on frontend

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#210]
We want to do the following improvements: 
Exemple of the page https://impreunapentrusanatate.ro/ro/clinics/centrul-medical-national-pentru-copii-din-shanghai 

- [x] If an item is null we should not show the label or icon.
- [x] Add country prefix to phone numbers displayed on this page
- [x] Instead of showing clinic link we should add the text **Website** that should link to the address completed by admin. This should open in a new tab. Ideal we add an icon to indicate that. Make sure to use rel=noopener.
- [x] Rename **Detalii Clinica** from where we show oncologie, hematologie etc to **Specializare Clinică**

**Comment by andreipetcu** [comment]
Done on development branch.

**Comment by mariusghitoiu** [comment]
Deployed in production.
