### ISSUE TITLE
Homepage adjustments 

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#211]
We want to do the following changes on homepage

- [x] Schimbari in sectiunea **Bine ai venit**

- De schimbat butoane “Solicită servicii” in “Solicită ajutor” si “Implică-te” in “Oferă ajutor”
- De modificat culoarea de la fundal buton “Solicită ajutor” din albastru in rosu (cod culoare AB1E2C); - _de vazut aici poate schimbam la toate butoanele_

- De modificat culoare de la fundal buton „Oferă ajutor"din verde in albastru (cod culoare: 2574B8);
- Butonul de Justify la texte nu functioneaza – rugam remediere  - _twill pune clasa **ql-align-justify** trebuie sa punem pentru ea Justify_ 
- De schimbat imaginea cu doctorul din stanga cu cea din arhiva atasata. 
[helpforhealth-poster.png.zip](https://github.com/code4romania/impreuna-pentru-sanatate/files/5873579/helpforhealth-poster.png.zip)

- [x] Sectiunea "Modalități prin care putem ajuta persoanele diagnosticate cu afecțiuni grave:"

- De schimbat culoare text “Modalitati prin care putem ajuta persoanele diangosticate cu afectiuni grave:” din negru in albastru (cod culoare: 2574B8);
- De folosit icon-urile din arhiva atasata. 
[Icons.zip](https://github.com/code4romania/impreuna-pentru-sanatate/files/5873686/Icons.zip)

- De pus pe fundal, in loc de imaginea cu sala de operatii, fundalul roz din arhiva atasata
[fundal-homepage.jpg.zip](https://github.com/code4romania/impreuna-pentru-sanatate/files/5873694/fundal-homepage.jpg.zip)
- La fiecare tip de serviciu oferit, pe fundal sa fie de la stanga la dreapta urmatoarele culori din poster: rosu (#de0124), portocaliu (#f5541a), albastru (#336cfe) si mov (#7233e9), iar textul din caseta sa fie scris cu alb, exact cum apare in documentul intitulat “IPS_square pentru servicii”;
[IPS_square_pentru_servicii (1).psd.zip](https://github.com/code4romania/impreuna-pentru-sanatate/files/5873799/IPS_square_pentru_servicii.1.psd.zip)

- [x] Renuntam la sectiunea "Despre Proiect"
- [x] Sectiune "Solicita Ajutor"

- Solicită ajutor pe fundal verde a devenit “Știri din sănătate”
- Structura rubricii este cea de la link-ul: https://impreunapentrusanatate.ro/ro/stiri 
- Butonul “Solicita aici” sa fie inlocuit cu “Citește mai departe”. - _ trebuie sa adaugam in twill posibilitatea de a pune si link-ul pe langa Titlu si text_
- culoarea verde de la sectiune sa fie modificata in rosu (cod culoare AB1E2C); 

- [x] Secțiune implica-te

- "Implică-te" pe fundal albastru a devenit “Comunitatea Solidarității”
- Butonul “Implica-te” sa fie inlocuit cu “Listă parteneri", iar cand se da click se va deschide pagina https://impreunapentrusanatate.ro/ro/parteneri

- [x] Logo-uri in footer

- De inlocuit logo M.A.M.E
[asociatia-mame-white.png.zip](https://github.com/code4romania/impreuna-pentru-sanatate/files/5873805/asociatia-mame-white.png.zip)
- de pus link pe Civiclabs -  https://civiclabs.ro/ro
- logo-urile partenerilor sa fie proportionale.

Update footer in #213

Documentul initial, din care am extras cele de mai sus, atasat.
[Sugestii modificari platforma- impreunapentrusanatate.docx](https://github.com/code4romania/impreuna-pentru-sanatate/files/5874023/Sugestii.modificari.platforma-.impreunapentrusanatate.docx)

**Comment by andreipetcu** [comment]
Done on branch issues/211_homepage_adjustments
Except the footer/logos/partners section which requires updates in twill prod

**Comment by mariusghitoiu** [comment]
Deployed.
