### ISSUE TITLE
Update main menu

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#212]
Meniu principal: vor ramane urmatoarele rubrici cu denumirile aferente, in aceasta ordine: 

- Despre proiect, Donează (sa fie anulat underline-ul din denumire), Solicită ajutor; Oferă ajutor, Clinici și spitale, Autentificare in loc de LOGIN Gazda, Contact, Ro/Engl

- Denumirea rubricilor sa fie cu albastrul din logo in momentul in care sunt active (cod culoare: 2574B8)

**Comment by andreipetcu** [comment]
Done on issues/212_update_main_menu branch

**Comment by mariusghitoiu** [comment]
Deployed in production.
