### ISSUE TITLE
Footer updates

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#213]
- [x] Renuntam la link “Parteneri” din footer. 

- [x] Linkul “Despre impreuna pentru sanatate” va fi inlocuit pagina nou creata "Despre proiect" ( https://impreunapentrusanatate.ro/cms/pages/8/edit ) ,
- [x]  “Întrebări frecvente” cu link catre noua pagina din twill https://impreunapentrusanatate.ro/cms/pages/9/edit
- [x] Ordinea rubricilor care apar in footer este urmatoarea: 

- Despre proiect 
- Întrebări frecvente 
- Media 
- Știri 
- Politica de confidențialitate
- Termeni și Condiții

- [x] Se va inlocui textul “Dacă ai nevoie de ajutor contactează Asociația M.A.M.E.” cu textul  “Pentru mai multe detalii, contactează Asociația M.A.M.E.”, iar textul sa fie alb, la fel si la Numărul de telefon, Email, Website.

**Comment by andreipetcu** [comment]
Done on branch issues/213_update_footer

**Comment by mariusghitoiu** [comment]
Released in production.
