### ISSUE TITLE
Schimbari formularul de la rubrica “Solicită ajutor” 

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#214]
Formularul de la rubrica “Solicită ajutor” sa fie schimbat ca in printscreen-ul atasat:

- Banda de alerta sa fie cu scris alb pe fundal albastru (cod culoare: 2574B8);
- Background formular sa fie inlocuit cu cel atasat, folosit si pe homepage
- Fundalul butonului de “Trimite solicitarea” sa fie culoarea rosie (cod culoare: AB1E2C);
- De pus diacritice peste tot in formular, iar toate substantivele sa fie articulate hotarat (Telefonul, Emailul etc)  
- Am simulat completarea formularului si, in situatia in care formularul este completat chiar de pacient, nu te lasa sa mergi mai departe si sa trimitic solicitarea daca nu completezi si rubricile ce tin de apartinatori (rubricile din dreapta nu trebuie sa fie obligatorii pentru aceasta situatie); - _de scos si * si in acelas timp sa ne asiguram ca nu apar probleme in admin unde sunt afisate_
- La detaliile legate de cazare, nu te lasa sa selectezi data in calendar; - _posibil sa fie ceva specific windows, pe mac nu am reprodus_
- Dupa ce se completeaza campurile din formular si se apasa butonul de Trimite solicitarea, persoana primeste mesajul cu “Îți mulțumim! …..”. De inlocuit cu cel de mai jos modificat si cu diacritice

> Îți mulțumim! 
> Formularul tău a fost transmis către Asociația M.A.M.E. În cel mai scurt timp, vei fi contactat de către un reprezentant al organizației pentru a discuta mai multe detalii legate de modalitățile prin care te putem ajuta.
> Dacă dorești să ne comunici și alte informații pe care nu le-ai transmis în formularul completat, te rugăm să ne trimiți un email la adresa: ajutor@asociatiamame.com
> 

![Printscreen Solicita ajutor (2)](https://user-images.githubusercontent.com/147089/105863358-7cc96180-5ff9-11eb-897b-fbdfbe0bf8fb.jpg)
![fundal-homepage](https://user-images.githubusercontent.com/147089/105863468-98cd0300-5ff9-11eb-9d27-e54c6b82ce15.jpg)

**Comment by andreipetcu** [comment]
Done on issues/214_update_request_help_form branch

**Comment by andreipetcu** [comment]
Except for the calendar picker issue

**Comment by mariusghitoiu** [comment]
@andreipetcu calendar related I found these: 
https://github.com/creativetimofficial/argon-design-system/issues/113
https://github.com/creativetimofficial/argon-design-system/commit/5f9734af6aee0f637396285cf33e37ffc1bf9c28

Still couldn't make it work for now.

**Comment by mariusghitoiu** [comment]
Looks good. Deployed in production.
