### ISSUE TITLE
Imbunatatiri formular Ofera Ajutor

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#215]
Formularul de la rubrica “Oferă ajutor” sa fie schimbat dupa cum urmeaza:

- [x] Background formular sa fie inlocuit cu cel atasat
- [x] Fundalul butonului de “Trimite solicitarea” sa fie culoarea albastra (cod culoare: 2574B8);
- [x] De pus diacritice peste tot in formular, iar substantivele sa fie toate articulate (Numarul de telefon, Emailul etc);
- [x] Dupa ce se completeaza campurile din formular si se apasa butonul de Trimite solicitarea, persoana primeste mesajul cu “Îți mulțumim! …..”. Trebuie inlocuit cu cel de mai jos, care are si diacritice

> Îți mulțumim! 
> Formularul tău a fost transmis către Asociația M.A.M.E. În cel mai scurt timp, vei fi contactat de către un reprezentant al organizației pentru a discuta mai multe detalii legate de modalitățile prin care te poți implica. 
> Dacă dorești să ne comunici și alte informații pe care nu le-ai transmis în formularul completat, te rugăm să ne trimiți un email la adresa: ajutor@asociatiamame.com
> 

![fundal-homepage](https://user-images.githubusercontent.com/147089/105865058-396ff280-5ffb-11eb-88ba-b0c2feb952de.jpg)
;

**Comment by andreipetcu** [comment]
Done on issues/215_update_provide_help_form branch

**Comment by mariusghitoiu** [comment]
Deployed.
