### ISSUE TITLE
IE 11 - promt user to get a different browser.

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#224]
Vrem să adăugăm un script js care detecteaza atunci cand siteul este accesat de pe Internet Explorer (orice versiune sau daca e mai simplu doar IE 11) si sa afiseze un mesaj de genul: 

`Browser-ul tău (Internet Explorer) este învechit și nu permite navigarea pe acest site. Pentru a putea accesa siteul te rugăm să descarci un browser modern`
Apoi punem lista de browsere cu link catre pagina de download a fiecaruia, ca aici
https://browser-update.org/

Nu vrem sa avem optiune de inchidere a acestui popup.

**Comment by mariusghitoiu** [comment]
<img width="1819" alt="Screen Shot 2021-04-02 at 3 51 45 PM" src="https://user-images.githubusercontent.com/147089/113417065-55ad5880-93cb-11eb-8818-bb908b1fd8e5.png">

@andreipetcu this is not implemented yet.

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
Done.
