### ISSUE TITLE
Reset page when filter is changed on clinics in frontend

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#235]
In this page https://impreunapentrusanatate.ro/ro/clinics? if we navigate to a specific page and then apply filters, we might not see results because the page number is kept. 
Ex: you are in page 4
You filter by country and city and have only one page o results. Nothing is shown. 

We need to reset the page number when a new filter is applied.

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
Tested on dev.

**Comment by mariusghitoiu** [comment]
Looks good, deployed in production.
