### ISSUE TITLE
Improvements on Audit Logs

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#243]
We need to make few improvements in this page: 
https://impreunapentrusanatate.ro/admin/audit-logs

1. We should not load all entries at once, and request one page at a time. 
2. Increase spacing for pages and other small visual adjustments to look good.

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
Deployed on live.
