### ISSUE TITLE
New fields for english version on clinics

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#247]
We need to be able to translate all clinic details in english so we need to do the following changes: 

- [x] Add 3 new fields in clinics table. 
- `description_en`, `additional_information_en`, `transport_details_en`

- [x] Add these new fields in admin on add/view/edit with the same options as their corespondent in romanian. They should alternate, RO field, EN field etc. 

- [x] In frontend. Get info from the english fields if site language is english. 

If there is a better approach overall, I am open to it.

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
@andreipetcu we need a new field for `clinic_name` in english as well. I missed this in my initial specs.

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
Deployed on live.
