### ISSUE TITLE
Add english translation for Clinics categories

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#248]
In clinic details page https://impreunapentrusanatate.ro/en/clinics/centrul-oncologic-institutul-marie-sklodowska-curie-filiala-gliwice-3 when shown in English, we need to translate these categories. 

Translations: 

Hematology - Hematology for adults
Hematology - Pediatric Hematology
Oncology - Oncology for adults
Oncology - Pediatric Oncology
Radiotherapy - Radiotherapy for adults
Radiotherapy - Radiotherapy for children
Bone Marrow Transplant - Pediatric Bone Marrow Transplant 
Bone Marrow Transplant - Bone Marrow Transplant for Adults

**Comment by andreipetcu** [comment]
Done on development branch.
Apply translations by running `$ php artisan db:seed --class=SpecialitiesTranslations`

**Comment by mariusghitoiu** [comment]
Looks good.

**Comment by mariusghitoiu** [comment]
Deployed in production.
