### ISSUE TITLE
Offer help form - bug fix / changes

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#258]
We have the following errors: 
![Eroare Ofera Ajutor](https://user-images.githubusercontent.com/147089/115283440-051c5600-a154-11eb-90c6-e0528c7c35af.png)
![Eroare 2_Ofera Ajutor](https://user-images.githubusercontent.com/147089/115283450-08afdd00-a154-11eb-8305-618f132b7ef1.png)

We should do the following changes: 

- [x] keep unique validation for email when when Cazare is checked. Because this will trigger an account creation. 
- [x] remove the prefix part from phone, and make it text field which allows + and numbers up to 12 characters. 
- [x] Investigate what triggers the 500 error.

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
It is live.
