### ISSUE TITLE
Update Clinici și Spitale

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#263]
- [ ] Sa apara tot prefix-ul la detalii clinica si la persoana de contact; - related with #252 
- [x] Cand esti pe o clinica, rubrica Detalii clinica (oncologie, hematologie etc) sa fie inlocuita cu Specialitate clinica, nu Specializare asa cum este acum;
- [x] Pentru varianta in limba engleza, sa fie creat si campul de persoana de contact deoarece, de multe ori, pe langa numele doctorului, am gasit si functia pe care acesta o detine in cadrul departamentului si e necesar sa o traducem

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
Released on live.
