### ISSUE TITLE
Change link in twill when new page is created

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#280]
It looks like there is an old url, ajutordeurgenta.ro, somewhere in settings that appears when a new twill page is created. 

We need to see from where it comes and change with impreunapentrusanatate.ro 

![Screenshot 2021-05-10 132917](https://user-images.githubusercontent.com/147089/117817586-6c6b8880-b270-11eb-8476-a64cce95be9b.png)

**Comment by andreipetcu** [comment]
@mariusghitoiu this seems to come from env APP_URL. can you please check?

**Comment by mariusghitoiu** [comment]
Fixed. APP_URL secret wasn't updated.
