### ISSUE TITLE
Fix homepage background 

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#282]
On "Stiri din domeniul sanatate" box, we want to extend the red background for the entire box at the bottom. 

<img width="1884" alt="Screen Shot 2021-05-18 at 4 29 55 PM" src="https://user-images.githubusercontent.com/147089/118659857-59b7fd00-b7f6-11eb-9138-af0a31677c25.png">

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
Released in production.
