### ISSUE TITLE
Remove the country prefix for phone from help request and offer help forms

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#285]
In this page we want to remove the country prefix dropdown for phone and update the phone filed to allow text as we did for other fields. 

https://impreunapentrusanatate.ro/ro/request-help 
https://impreunapentrusanatate.ro/ro/offer-help

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
Released on live.
