### ISSUE TITLE
Updates on email to admin when help resource is added. 

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#320]
With this issue we need to address the following two aspects: 

- [x] Correct the link in `HelpResourceInfoAdminMail` email, where we set the ID of resource instead of the id of the help resource type. In this case if there are multiple help resources the user has to offer in an entry, we need to add different links for each of them in the email. 
- [x] Send this email to ovidiu.dinica@asociatiamame.com as well.

**Comment by andreipetcu** [comment]
Done

**Comment by mariusghitoiu** [comment]
Released. Great success!
